### PR TITLE
[Good First Issue] Fix the invalid url

### PR DESCRIPTION
**Pull request by Liyulingyue**
### PR types

Others 
### PR changes

Docs 
### Description

https://github.com/PaddlePaddle/PaddleSeg/issues/3054#issuecomment-1577822487

### CODE REVIEW

**Comment by Liyulingyue** [comment]
@shiyutang

**Review by shiyutang — APPROVED** [review]
LGTM

**Comment by shiyutang** [comment]
可以提交到develop分支. @Liyulingyue

**Comment by Liyulingyue** [comment]
> 可以提交到develop分支. @Liyulingyue

develop链接正常，没有失效

**Pull request merged**
